services:
  - type: web
    name: TrailBuddy
    runtime: python
    pythonVersion: 3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false